---
- name: "SQL Script Execution"
  hosts: all
  
  tasks:
    - win_command: sqlcmd -S {{ NODO-WINSER2019\SQLEXPRESS }} -i "C:\\Users\\Administrator\\Documents\\createdbtesting.sql"
      register: sqlcmd_out
