---
- name: add user
  hosts: all
  gather_facts: false
  
  tasks:
    - name: instalar paqueteria a vdi enfermeria
      win_chocolatey:
        name:
        - vscode
        - git
        - chromium
        - dropbox
        - docker-desktop
        state: latest
